name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: List empty folder
        run: ls -l
      - uses: actions/checkout@v2
      - name: List complete folder
        run: ls -l
