name: Hello World Training Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  greet:
    env:
      NAME: "John Doe"
    runs-on: ubuntu-latest
    steps:
      - name: List empty folder
        run: ls -l
      - uses: actions/checkout@v2
      - name: List complete folder
        run: ls -l
      - name: Run a multi-line script
        run: |
          echo "Hello $NAME"
          echo "Hello $GITHUB_ACTOR"
